### ISSUE TITLE
Windows keeps deleting the rar file saying that "virus is detected"

### ISSUE THREAD

**Issue by giriteja94495** [meik97/XSpotify#14]

**Comment by dzek69** [comment]
Can confirm, detected as: `Trojan:Win32/Wacatac.D!ml`

`file: D:\Downloads\Vivaldi\XSpotify.rar->XSpotify\XSpotify.exe`

What is suspicious that 474KB file contains a dll file (with other files as well) that extracts to 147MB

I'd suggest not to use this.

**Comment by dzek69** [comment]
XSpotify.exe VirusTotal report: https://www.virustotal.com/gui/file/928f9112ddc790e9c8c5a0ed7b642570239db92da543a9336cf6a12777f5f77f/detection

token.exe (small, iconless file, suspicious as well) VT report:
https://www.virustotal.com/gui/file/271170b8668a0df75416d9f0f5cd599350ae37ba4ed2f8e85dd71429393a53a0/detection

rar file report:
https://www.virustotal.com/gui/file/e93e40a311557162ec3b7fc9a0410974287b53f4b2f43f7013bece1703c3777e/detection

can't generate report for DLL file because it's too big

**everything here seems suspicious and like a trojan**

**Comment by MihailCosmin** [comment]
I tried this XSpotify and suddenly on my desktop this app appeared: "MailStore.exe" which I definitely did not install...
This is indeed very strange

**Comment by dzek69** [comment]
It's time to reinstall your OS I think.

If you want to do a backup of your files, make sure to remove all exe and dll files from the backup.

Oh, and I'd suggest to do if immediately and disconnect from the Internet in case of [ransomware](https://en.wikipedia.org/wiki/Ransomware)

**Comment by meik97** [comment]
You can simply build the files yourself with the source code if you want to be 100% sure.

Its a false-positive.

**Comment by MihailCosmin** [comment]
Can you at least tell why is the windows DLL so big and the source file only a few kb ?

**Comment by fortender** [comment]
According to the project settings the code is compiled with command line option /O2 which prioritizes compilation speed over file size. This outputs a file that consists of about 99% of zeros. That's why the archive is able to compress it to a minimum. Use /O1 command line parameter instead and you will get a much smaller file.

**Comment by meik97** [comment]
As @fortender  has mentioned already, its a compiler option.
If you compile it with /O1 you should get a smaller size.

Also, only download XSpotify from this GitHub. I have already seen other websites linking the files.
